package com.example.model

object MotivationalQuotes {
    val quotes = listOf(
        "Believe you can and you're halfway there.",
        "Act as if what you do makes a difference.",
        "Success is not final, failure is not fatal.",
        "Never bend your head. Always hold it high.",
        "What you get by achieving your goals is not as important as what you become.",
        "It is during our darkest moments that we must focus to see the light.",
        "Believe in yourself and all that you are.",
        "Keep your face always toward the sunshine.",
        "You define your own life. Don't let other people write your script.",
        "You are never too old to set another goal.",
        "Spread love everywhere you go.",
        "Warmth is the vital element for the growing plant.",
        "Out of difficulties grow miracles.",
        "Be yourself; everyone else is already taken.",
        "You must do the things you think you cannot do.",
        "If you can dream it, you can do it.",
        "Start where you are. Use what you have. Do what you can.",
        "Keep going. Each step is progress.",
        "The best way to predict the future is to create it.",
        "Mistakes are proof that you are trying.",
        "Your limit is only your imagination.",
        "Push yourself, because no one else is going to do it for you.",
        "Great things never come from comfort zones.",
        "Dream it. Wish it. Do it.",
        "Success doesn't just find you. You have to go out and get it.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream bigger. Do bigger.",
        "Don't stop when you're tired. Stop when you're done.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Do something today that your future self will thank you for.",
        "Little things make big days.",
        "It's going to be hard, but hard does not mean impossible.",
        "Don't wait for opportunity. Create it.",
        "Sometimes later becomes never. Do it now.",
        "Great things take time.",
        "Be a voice, not an echo.",
        "Focus on being productive instead of busy.",
        "You are capable of amazing things.",
        "Rise up and attack the day with enthusiasm.",
        "Today is another chance to get better.",
        "Happiness is a warm cup of peace.",
        "A champion is defined not by their wins but by how they can recover.",
        "Difficult roads often lead to beautiful destinations.",
        "The secret of getting ahead is getting started.",
        "Your energy is your power. Protect it.",
        "Small steps in the right direction can turn into the biggest step of your life.",
        "You do not find the happy life. You make it.",
        "Make each day your masterpiece.",
        "No pressure, no diamonds.",
        "Every moment is a fresh beginning."
    )

    private val idTranslations = mapOf(
        "Believe you can and you're halfway there." to "Percayalah Anda bisa dan Anda sudah setengah jalan.",
        "Act as if what you do makes a difference." to "Bertindaklah seolah apa yang Anda lakukan membuat perbedaan.",
        "Success is not final, failure is not fatal." to "Kesuksesan bukanlah akhir, kegagalan tidaklah fatal.",
        "Never bend your head. Always hold it high." to "Jangan pernah menundukkan kepala. Selalu tegakkan kepala Anda.",
        "What you get by achieving your goals is not as important as what you become." to "Apa yang Anda dapatkan dengan mencapai tujuan tidak sepenting menjadi apa Anda.",
        "It is during our darkest moments that we must focus to see the light." to "Di saat-saat tergelap kita harus fokus untuk melihat cahaya.",
        "Believe in yourself and all that you are." to "Percayalah pada diri sendiri dan semua yang Anda miliki.",
        "Keep your face always toward the sunshine." to "Jaga wajah Anda selalu menghadap ke arah sinar matahari.",
        "You define your own life. Don't let other people write your script." to "Anda menentukan hidup Anda sendiri. Jangan biarkan orang lain menulis naskah Anda.",
        "You are never too old to set another goal." to "Anda tidak pernah terlalu tua untuk menetapkan tujuan lain.",
        "Spread love everywhere you go." to "Sebarkan cinta ke mana pun Anda pergi.",
        "Warmth is the vital element for the growing plant." to "Kehangatan adalah elemen vital bagi tanaman yang tumbuh.",
        "Out of difficulties grow miracles." to "Dari kesulitan tumbuh keajaiban.",
        "Be yourself; everyone else is already taken." to "Jadilah diri sendiri; semua orang lain sudah ada yang memiliki.",
        "You must do the things you think you cannot do." to "Anda harus melakukan hal-hal yang Anda pikir tidak bisa dilakukan.",
        "If you can dream it, you can do it." to "Jika Anda bisa memimpikannya, Anda bisa melakukannya.",
        "Start where you are. Use what you have. Do what you can." to "Mulailah dari mana Anda berada. Gunakan apa yang Anda miliki. Lakukan apa yang Anda bisa.",
        "Keep going. Each step is progress." to "Teruslah melangkah. Setiap langkah adalah kemajuan.",
        "The best way to predict the future is to create it." to "Cara terbaik untuk memprediksi masa depan adalah dengan menciptakannya.",
        "Mistakes are proof that you are trying." to "Kesalahan adalah bukti bahwa Anda sedang berusaha.",
        "Your limit is only your imagination." to "Batas Anda hanyalah imajinasi Anda.",
        "Push yourself, because no one else is going to do it for you." to "Dorong diri Anda sendiri, karena tidak ada orang lain yang akan melakukannya untuk Anda.",
        "Great things never come from comfort zones." to "Hal-hal hebat tidak pernah datang dari zona nyaman.",
        "Dream it. Wish it. Do it." to "Mimpikanlah. Harapkanlah. Lakukanlah.",
        "Success doesn't just find you. You have to go out and get it." to "Kesuksesan tidak hanya menemukan Anda. Anda harus keluar dan mendapatkannya.",
        "The harder you work for something, the greater you'll feel when you achieve it." to "Semakin keras Anda bekerja untuk sesuatu, semakin besar perasaan Anda saat mencapainya.",
        "Dream bigger. Do bigger." to "Bermimpilah lebih besar. Lakukan hal yang lebih besar.",
        "Don't stop when you're tired. Stop when you're done." to "Jangan berhenti saat Anda lelah. Berhentilah saat Anda selesai.",
        "Wake up with determination. Go to bed with satisfaction." to "Bangun dengan tekad. Pergi tidur dengan kepuasan.",
        "Do something today that your future self will thank you for." to "Lakukan sesuatu hari ini yang akan membuat diri masa depan Anda berterima kasih.",
        "Little things make big days." to "Hal-hal kecil membuat hari-hari menjadi besar.",
        "It's going to be hard, but hard does not mean impossible." to "Ini akan sulit, tetapi sulit tidak berarti mustahil.",
        "Don't wait for opportunity. Create it." to "Jangan menunggu kesempatan. Ciptakanlah.",
        "Sometimes later becomes never. Do it now." to "Terkadang nanti menjadi tidak pernah. Lakukan sekarang.",
        "Great things take time." to "Hal-hal hebat membutuhkan waktu.",
        "Be a voice, not an echo." to "Jadilah suara, bukan gema.",
        "Focus on being productive instead of busy." to "Fokuslah untuk menjadi produktif daripada sibuk.",
        "You are capable of amazing things." to "Anda mampu melakukan hal-hal luar biasa.",
        "Rise up and attack the day with enthusiasm." to "Bangkitlah dan hadapi hari dengan antusiasme.",
        "Today is another chance to get better." to "Hari ini adalah kesempatan lain untuk menjadi lebih baik.",
        "Happiness is a warm cup of peace." to "Kebahagiaan adalah secangkir kehangatan kedamaian.",
        "A champion is defined not by their wins but by how they can recover." to "Seorang juara ditentukan bukan oleh kemenangan mereka tetapi bagaimana mereka bangkit kembali.",
        "Difficult roads often lead to beautiful destinations." to "Jalan yang sulit sering kali berujung pada tujuan yang indah.",
        "The secret of getting ahead is getting started." to "Rahasia untuk maju adalah dengan memulai.",
        "Your energy is your power. Protect it." to "Energi Anda adalah kekuatan Anda. Lindungi itu.",
        "Small steps in the right direction can turn into the biggest step of your life." to "Langkah kecil ke arah yang benar bisa menjadi langkah terbesar dalam hidup Anda.",
        "You do not find the happy life. You make it." to "Anda tidak menemukan kehidupan yang bahagia. Anda menciptakannya.",
        "Make each day your masterpiece." to "Jadikan setiap hari sebagai mahakarya Anda.",
        "No pressure, no diamonds." to "Tanpa tekanan, tidak ada berlian.",
        "Every moment is a fresh beginning." to "Setiap momen adalah awal yang baru."
    )

    private val esTranslations = mapOf(
        "Believe you can and you're halfway there." to "Cree que puedes y habrás recorrido la mitad del camino.",
        "Act as if what you do makes a difference." to "Actúa como si lo que haces marcara la diferencia.",
        "Success is not final, failure is not fatal." to "El éxito no es el final, el fracaso no es fatal.",
        "Never bend your head. Always hold it high." to "Nunca agaches la cabeza. Mantenla siempre en alto.",
        "What you get by achieving your goals is not as important as what you become." to "Lo que obtienes al lograr tus metas no es tan importante como en lo que te conviertes.",
        "It is during our darkest moments that we must focus to see the light." to "Es en nuestros momentos más oscuros cuando debemos enfocarnos para ver la luz.",
        "Believe in yourself and all that you are." to "Cree en ti mismo y en todo lo que eres.",
        "Keep your face always toward the sunshine." to "Mantén tu rostro siempre hacia la luz del sol.",
        "You define your own life. Don't let other people write your script." to "Tú defines tu propia vida. No dejes que otros escriban tu guion.",
        "You are never too old to set another goal." to "Nunca eres demasiado viejo para establecer otra meta.",
        "Spread love everywhere you go." to "Difunde amor por dondequiera que vayas.",
        "Warmth is the vital element for the growing plant." to "El calor es el elemento vital para la planta en crecimiento.",
        "Out of difficulties grow miracles." to "De las dificultades crecen milagros.",
        "Be yourself; everyone else is already taken." to "Sé tú mismo; todos los demás ya están ocupados.",
        "You must do the things you think you cannot do." to "Debes hacer las cosas que crees que no puedes hacer.",
        "If you can dream it, you can do it." to "Si puedes soñarlo, puedes hacerlo.",
        "Start where you are. Use what you have. Do what you can." to "Empieza donde estás. Usa lo que tienes. Haz lo que puedas.",
        "Keep going. Each step is progress." to "Sigue adelante. Cada paso es un progreso.",
        "The best way to predict the future is to create it." to "La mejor manera de predecir el futuro es creándolo.",
        "Mistakes are proof that you are trying." to "Los errores son la prueba de que lo estás intentando.",
        "Your limit is only your imagination." to "Tu límite es sólo tu imaginación.",
        "Push yourself, because no one else is going to do it for you." to "Esfuérzate tú mismo, porque nadie más lo hará por ti.",
        "Great things never come from comfort zones." to "Las cosas grandes nunca vienen de zonas de confort.",
        "Dream it. Wish it. Do it." to "Suéñalo. Deséalo. Hazlo.",
        "Success doesn't just find you. You have to go out and get it." to "El éxito no te encuentra. Tienes que salir a buscarlo.",
        "The harder you work for something, the greater you'll feel when you achieve it." to "Cuanto más trabajes por algo, mejor te sentirás cuando lo logres.",
        "Dream bigger. Do bigger." to "Sueña más grande. Haz más grande.",
        "Don't stop when you're tired. Stop when you're done." to "No pares cuando estés cansado. Para cuando hayas terminado.",
        "Wake up with determination. Go to bed with satisfaction." to "Despiértate con determinación. Acuéstate con satisfacción.",
        "Do something today that your future self will thank you for." to "Haz algo hoy de lo que tu futuro yo te esté agradecido.",
        "Little things make big days." to "Las cosas pequeñas hacen días grandes.",
        "It's going to be hard, but hard does not mean impossible." to "Va a ser difícil, pero difícil no significa imposible.",
        "Don't wait for opportunity. Create it." to "No esperes la oportunidad. Créala.",
        "Sometimes later becomes never. Do it now." to "A veces más tarde se convierte en nunca. Hazlo ahora.",
        "Great things take time." to "Las cosas grandes toman tiempo.",
        "Be a voice, not an echo." to "Sé una voz, no un eco.",
        "Focus on being productive instead of busy." to "Enfócate en ser productivo en lugar de ocupado.",
        "You are capable of amazing things." to "Eres capaz de cosas increíbles.",
        "Rise up and attack the day with enthusiasm." to "Levántate y ataca el día con entusiasmo.",
        "Today is another chance to get better." to "Hoy es otra oportunidad para mejorar.",
        "Happiness is a warm cup of peace." to "La felicidad es una taza cálida de paz.",
        "A champion is defined not by their wins but by how they can recover." to "Un campeón se define no por sus victorias sino por cómo se recupera.",
        "Difficult roads often lead to beautiful destinations." to "Los caminos difíciles a menudo conducen a destinos hermosos.",
        "The secret of getting ahead is getting started." to "El secreto para salir adelante es comenzar.",
        "Your energy is your power. Protect it." to "Tu energía es tu poder. Protégela.",
        "Small steps in the right direction can turn into the biggest step of your life." to "Pequeños pasos en la dirección correcta pueden convertirse en el paso más grande de tu vida.",
        "You do not find the happy life. You make it." to "No encuentras la vida feliz. Tú la creas.",
        "Make each day your masterpiece." to "Haz de cada día tu obra maestra.",
        "No pressure, no diamonds." to "Sin presión, no hay diamantes.",
        "Every moment is a fresh beginning." to "Cada momento es un nuevo comienzo."
    )

    private val frTranslations = mapOf(
        "Believe you can and you're halfway there." to "Croyez que vous le pouvez et vous êtes déjà à mi-chemin.",
        "Act as if what you do makes a difference." to "Agissez comme si ce que vous faites faisait une différence.",
        "Success is not final, failure is not fatal." to "Le succès n'est pas définitif, l'échec n'est pas mortel.",
        "Never bend your head. Always hold it high." to "Ne baissez jamais la tête. Gardez-la toujours haute.",
        "What you get by achieving your goals is not as important as what you become." to "Ce que vous obtenez en atteignant vos objectifs n'est pas aussi important que ce que vous devenez.",
        "It is during our darkest moments that we must focus to see the light." to "C'est dans nos moments les plus sombres que nous devons nous concentrer pour voir la lumière.",
        "Believe in yourself and all that you are." to "Croyez en vous et en tout ce que vous êtes.",
        "Keep your face always toward the sunshine." to "Gardez toujours votre visage tourné vers le soleil.",
        "You define your own life. Don't let other people write your script." to "Vous définissez votre propre vie. Ne laissez pas les autres écrire votre scénario.",
        "You are never too old to set another goal." to "Vous n'êtes jamais trop vieux pour vous fixer un autre objectif.",
        "Spread love everywhere you go." to "Répandez l'amour partout où vous allez.",
        "Warmth is the vital element for the growing plant." to "La chaleur est l'élément vital pour la plante en croissance.",
        "Out of difficulties grow miracles." to "Des difficultés naissent les miracles.",
        "Be yourself; everyone else is already taken." to "Soyez vous-même ; tous les autres sont déjà pris.",
        "You must do the things you think you cannot do." to "Vous devez faire les choses que vous pensez ne pas pouvoir faire.",
        "If you can dream it, you can do it." to "Si vous pouvez le rêver, vous pouvez le faire.",
        "Start where you are. Use what you have. Do what you can." to "Commencez là où vous êtes. Utilisez ce que vous avez. Faites ce que vous pouvez.",
        "Keep going. Each step is progress." to "Continuez d'avancer. Chaque étape est un progrès.",
        "The best way to predict the future is to create it." to "La meilleure façon de prédire l'avenir est de le créer.",
        "Mistakes are proof that you are trying." to "Les erreurs sont la preuve que vous essayez.",
        "Your limit is only your imagination." to "Votre seule limite est votre imagination.",
        "Push yourself, because no one else is going to do it for you." to "Dépassez-vous, car personne d'autre ne le fera pour vous.",
        "Great things never come from comfort zones." to "Les grandes choses ne viennent jamais des zones de confort.",
        "Dream it. Wish it. Do it." to "Rêvez-le. Souhaitez-le. Faites-le.",
        "Success doesn't just find you. You have to go out and get it." to "Le succès ne vous trouve pas par hasard. Vous devez aller le chercher.",
        "The harder you work for something, the greater you'll feel when you achieve it." to "Plus vous travaillez dur pour quelque chose, plus vous serez fier de l'avoir accompli.",
        "Dream bigger. Do bigger." to "Rêvez plus grand. Faites plus grand.",
        "Don't stop when you're tired. Stop when you're done." to "Ne vous arrêtez pas quand vous êtes fatigué. Arrêtez-vous quand vous avez fini.",
        "Wake up with determination. Go to bed with satisfaction." to "Réveillez-vous avec détermination. Couchez-vous avec satisfaction.",
        "Do something today that your future self will thank you for." to "Faites quelque chose aujourd'hui pour lequel votre futur moi vous remerciera.",
        "Little things make big days." to "Les petites choses font les grands jours.",
        "It's going to be hard, but hard does not mean impossible." to "Ce sera dur, mais dur ne veut pas dire impossible.",
        "Don't wait for opportunity. Create it." to "N'attendez pas l'opportunité. Créez-la.",
        "Sometimes later becomes never. Do it now." to "Parfois, plus tard devient jamais. Faites-le maintenant.",
        "Great things take time." to "Les grandes choses prennent du temps.",
        "Be a voice, not an echo." to "Soyez une voix, pas un écho.",
        "Focus on being productive instead of busy." to "Concentrez-vous sur la productivité plutôt que sur l'occupation.",
        "You are capable of amazing things." to "Vous êtes capable de choses incroyables.",
        "Rise up and attack the day with enthusiasm." to "Levez-vous et attaquez la journée avec enthousiasme.",
        "Today is another chance to get better." to "Aujourd'hui est une autre chance de s'améliorer.",
        "Happiness is a warm cup of peace." to "Le bonheur est une tasse chaude de paix.",
        "A champion is defined not by their wins but by how they can recover." to "Le champion se définit non pas par ses victoires mais par sa capacité à se relever.",
        "Difficult roads often lead to beautiful destinations." to "Les chemins difficiles mènent souvent à de belles destinations.",
        "The secret of getting ahead is getting started." to "Le secret pour avancer est de commencer.",
        "Your energy is your power. Protect it." to "Votre énergie est votre pouvoir. Protégez-la.",
        "Small steps in the right direction can turn into the biggest step of your life." to "De petits pas dans la bonne direction peuvent devenir le plus grand pas de votre vie.",
        "You do not find the happy life. You make it." to "On ne trouve pas la vie heureuse. On la crée.",
        "Make each day your masterpiece." to "Faites de chaque jour votre chef-d'œuvre.",
        "No pressure, no diamonds." to "Pas de pression, pas de diamants.",
        "Every moment is a fresh beginning." to "Chaque moment est un nouveau départ."
    )

    private val deTranslations = mapOf(
        "Believe you can and you're halfway there." to "Glaube daran, dass du es kannst, und du hast den halben Weg geschafft.",
        "Act as if what you do makes a difference." to "Handle so, als ob dein Handeln einen Unterschied macht.",
        "Success is not final, failure is not fatal." to "Erfolg ist nicht endgültig, Scheitern ist nicht fatal.",
        "Never bend your head. Always hold it high." to "Senke niemals deinen Kopf. Halte ihn immer hoch.",
        "What you get by achieving your goals is not as important as what you become." to "Was du durch das Erreichen deiner Ziele erhältst, ist nicht so wichtig wie das, was du wirst.",
        "It is during our darkest moments that we must focus to see the light." to "In unseren dunkelsten Momenten müssen wir uns konzentrieren, um das Licht zu sehen.",
        "Believe in yourself and all that you are." to "Glaube an dich selbst und an alles, was du bist.",
        "Keep your face always toward the sunshine." to "Wende dein Gesicht immer der Sonne zu.",
        "You define your own life. Don't let other people write your script." to "Du bestimmst dein eigenes Leben. Lass andere nicht dein Drehbuch schreiben.",
        "You are never too old to set another goal." to "Du bist nie zu alt, um dir ein neues Ziel zu setzen.",
        "Spread love everywhere you go." to "Verbreite Liebe, wohin du auch gehst.",
        "Warmth is the vital element for the growing plant." to "Wärme ist das lebenswichtige Element für die wachsende Pflanze.",
        "Out of difficulties grow miracles." to "Aus Schwierigkeiten wachsen Wunder.",
        "Be yourself; everyone else is already taken." to "Sei du selbst; alle anderen sind bereits vergeben.",
        "You must do the things you think you cannot do." to "Du musst die Dinge tun, von denen du glaubst, sie nicht tun zu können.",
        "If you can dream it, you can do it." to "Wenn du es träumen kannst, kannst du es auch tun.",
        "Start where you are. Use what you have. Do what you can." to "Fange dort an, wo du bist. Nutze, was du hast. Tue, was du kannst.",
        "Keep going. Each step is progress." to "Mach weiter. Jeder Schritt ist ein Fortschritt.",
        "The best way to predict the future is to create it." to "Der beste Weg, die Zukunft vorherzusagen, ist, sie selbst zu gestalten.",
        "Mistakes are proof that you are trying." to "Fehler sind der Beweis dafür, dass du es versuchst.",
        "Your limit is only your imagination." to "Deine Grenze ist nur deine Fantasie.",
        "Push yourself, because no one else is going to do it for you." to "Fordere dich selbst heraus, denn niemand sonst wird es für dich tun.",
        "Great things never come from comfort zones." to "Großartige Dinge kommen nie aus der Komfortzone.",
        "Dream it. Wish it. Do it." to "Träume es. Wünsche es. Tue es.",
        "Success doesn't just find you. You have to go out and get it." to "Erfolg findet dich nicht einfach. Du musst hinausgehen und ihn dir holen.",
        "The harder you work for something, the greater you'll feel when you achieve it." to "Je härter für etwas gearbeitet wird, desto besser fühlt man sich, wenn es geschafft ist.",
        "Dream bigger. Do bigger." to "Träume größer. Tue Größeres.",
        "Don't stop when you're tired. Stop when you're done." to "Hör nicht auf, wenn du müde bist. Hör auf, wenn du fertig bist.",
        "Wake up with determination. Go to bed with satisfaction." to "Wach mit Entschlossenheit auf. Geh mit Zufriedenheit ins Bett.",
        "Do something today that your future self will thank you for." to "Tue heute etwas, wofür dein zukünftiges Ich dir danken wird.",
        "Little things make big days." to "Kleine Dinge machen große Tage.",
        "It's going to be hard, but hard does not mean impossible." to "Es wird schwer sein, aber schwer bedeutet nicht unmöglich.",
        "Don't wait for opportunity. Create it." to "Warte nicht auf Gelegenheiten. Erschaffe sie.",
        "Sometimes later becomes never. Do it now." to "Manchmal wird aus Später ein Nie. Tue es jetzt.",
        "Great things take time." to "Großartige Dinge brauchen Zeit.",
        "Be a voice, not an echo." to "Sei eine Stimme, kein Echo.",
        "Focus on being productive instead of busy." to "Konzentriere dich darauf, produktiv zu sein, anstatt nur beschäftigt.",
        "You are capable of amazing things." to "Du bist zu erstaunlichen Dingen fähig.",
        "Rise up and attack the day with enthusiasm." to "Steh auf und gehe den Tag mit Begeisterung an.",
        "Today is another chance to get better." to "Heute ist eine neue Chance, besser zu werden.",
        "Happiness is a warm cup of peace." to "Glück ist eine warme Tasse Frieden.",
        "A champion is defined not by their wins but by how they can recover." to "Ein Champion definiert sich nicht über seine Siege, sondern darüber, wie er sich erholt.",
        "Difficult roads often lead to beautiful destinations." to "Schwierige Wege führen oft zu wunderschönen Zielen.",
        "The secret of getting ahead is getting started." to "Der beste Weg voranzukommen ist anzufangen.",
        "Your energy is your power. Protect it." to "Deine Energie ist deine Kraft. Schütze sie.",
        "Small steps in the right direction can turn into the biggest step of your life." to "Kleine Schritte in die richtige Richtung können der größte Schritt deines Lebens werden.",
        "You do not find the happy life. You make it." to "Du findest kein glückliches Leben. Du erschaffst es selbst.",
        "Make each day your masterpiece." to "Mach jeden Tag zu deinem Meisterwerk.",
        "No pressure, no diamonds." to "Ohne Druck gibt es keine Diamanten.",
        "Every moment is a fresh beginning." to "Jeder Moment ist ein neuer Anfang."
    )

    fun t(quote: String, lang: String): String {
        return when (lang) {
            "Indonesian" -> idTranslations[quote] ?: quote
            "Spanish" -> esTranslations[quote] ?: quote
            "French" -> frTranslations[quote] ?: quote
            "German" -> deTranslations[quote] ?: quote
            else -> quote
        }
    }
}
